apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkaclusters.kafka.stackable.de
spec:
  group: kafka.stackable.de
  names:
    kind: KafkaCluster
    plural: kafkaclusters
    singular: kafkacluster
    shortNames:
      - kafka
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                  enum: [ 2.6.0 ]
                brokers:
                  type: array
                  items:
                    type: object
                    properties:
                      node_name:
                        type: string
                zooKeeperReference:
                  type: string
              required: [ "version", "brokers", "zooKeeperReference" ]
            status:
               type: object
               properties:
                 is_bad:
                   type: boolean
      subresources:
         status: {}
