[package]
name = "stackable-kafka-operator"
version = "0.1.0"
authors = ["Lars Francke <lars.francke@stackable.de>"]
edition = "2018"

[dependencies]
stackable-kafka-crd = { path = "../crd" }
stackable-operator = { git = "https://github.com/lfrancke/operator-rs.git", branch="start" }
stackable-zookeeper-crd = { git="https://github.com/lfrancke/zookeeper-operator.git", branch="start" }

futures = "0.3"
handlebars = "3.5"
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_18"] } # 1.19 and k8s-openapi 0.10 are not supported in kube 0.43 yet, they will be in the next released version
kube = { version = "0.43", default-features = false, features = ["derive"] }
kube-runtime = "0.43.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros"] }
tracing = "0.1"
